CREATE TABLE IF NOT EXISTS images
(
    PHOTO_ID INTEGER generated by default as identity primary key,
    FILE_PATH VARCHAR not null,
    FILE_EXTENSION VARCHAR not null,
    FILE_SIZE BIGINT not null,
    MEDIA_TYPE VARCHAR not null

);