CREATE TABLE IF NOT EXISTS users
(
    ID INTEGER generated by default as identity primary key,
    FIRST_NAME VARCHAR(255) NOT NULL,
    SUR_NAME VARCHAR(255) NOT NULL,
    LAST_NAME   VARCHAR(255) NOT NULL,
    BIRTH_DATE   VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) UNIQUE,
    PHONE   VARCHAR(255) NOT NULL,
    ROLE        VARCHAR(255) NOT NULL,
    PASSWORD  VARCHAR(255) NOT NULL,
    PHOTO_ID   INTEGER references images (PHOTO_ID) on delete set null
    );
INSERT INTO users (FIRST_NAME, SUR_NAME, LAST_NAME, BIRTH_DATE, EMAIL, PHONE, ROLE, PASSWORD, PHOTO_ID)
VALUES ('Иван', 'Сидоров', 'Иванович', '1990-01-01', 'ivan@example.com', '+1234567890', 'admin', 'securePassword123', NULL);






